### ISSUE TITLE
ThomasHaile: Week 2, Incremental Devlopment

### ISSUE THREAD

**Issue by thomashaile** [HackYourFutureBelgium/class-8#102]
------------------------------------------------------------------------------------
[week-2-Homework-Link](https://github.com/HackYourFutureBelgium/homework-submission#homework-issues)
-----------------------------------------------------------------------------------

### Prep Work
- [x] Inspecting the DOM
- [x] Read through this site And practice studying some HTML/CSS here
### HTML & CSS
- [x] What is Responsive Design?
Code Review
- [x] code review: Take a look through this page from Study
### Git, GitHub & GitKraken
- [x] git & github for poets
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits

### Name of Project:
- [x] Code-Along
[repository](https://github.com/thomashaile/app-theme)
[live demo](https://thomashaile.github.io/app-theme/)
- [step 1-branch-updating readme and creating dev-strategy](https://github.com/thomashaile/app-theme/tree/step-1-updating-readme-and-creating-development-strategy)
- [step 2-branch-creating the index-home page](https://github.com/thomashaile/app-theme/tree/step-2-creating-simple-index(home)-page-with-basic-structure)
- [step 3-branch-creating/adding the header, nav and footer to the homepage](https://github.com/thomashaile/app-theme/tree/step-3-creating-the-defferent-sections-index(homepage))
- [step 4-branch-adding all the remaining sections in homepage/index](https://github.com/thomashaile/app-theme/tree/step-4-creating-all-sections-in-index(homepage))
- [step 5-branch-creating about page](https://github.com/thomashaile/app-theme/tree/step-5-creating-the-about-page)
- [step 6-branch-creating services page](https://github.com/thomashaile/app-theme/tree/step-6-creating-services-html-page)
- [step 7-branch-creating contact page](https://github.com/thomashaile/app-theme/tree/step-7-creating-contact-page-with-contents)
- [step 8-branch-creating the css stylesheet file](https://github.com/thomashaile/app-theme/tree/step-8-creating-the-css-file)
- [step 9-branch-adding flexbox and font awsome](https://github.com/thomashaile/app-theme/tree/step-9-adding-flexbox-and-fontowsome-css)

### Exercises:

- [x] Sign in to FreeCodeCamp using your GitHub account:
-  [x] Complete all 4 of FreeCodeCamp's Responsive Web Design Principles challenges.[challenges](https://www.freecodecamp.org/thomashaile)
-  [x] Turn on your public portfolio (if you haven't yet)[myprofile](https://www.freecodecamp.org/thomashaile)
- [X] Fork and Clone HTML-CSS-Practice-Problems (if you haven't already):
-  [x] Turn on GitHub Pages_
-  [x] Complete the exercises in ./level-2_
-  [x] Fork and Clone css-exercises
-  [x] Turn on GitHub Pages
-  [x] Complete exercise-3, exercise-4 and exercise-5

- [x] HTML&CSS_Practice_problems_level2: [repo](https://github.com/thomashaile/HTML-CSS-Practice-Problems/tree/master/level-2), [live ](https://thomashaile.github.io/HTML-CSS-Practice-Problems/level-2/)
- [x] CSS_Exrecices_level-3: [repo](https://github.com/thomashaile/css-exercises/tree/master/exercise-3), [live (Exercise-3)](https://thomashaile.github.io/css-exercises/exercise-3/)
- [x] CSS_Exrecices_level-4: [repo](https://github.com/thomashaile/css-exercises/tree/master/exercise-4), [live (Exercise-4)](https://thomashaile.github.io/css-exercises/exercise-4/)
- [x] CSS_Exrecices_level-5: [repo](https://github.com/thomashaile/css-exercises/tree/master/exercise-5), [live (Exercise-5)](https://thomashaile.github.io/css-exercises/exercise-5/)

**Comment by idogrusoz** [comment]
Very good work and very nice and clean code.

- Try to improve your README(Imagine that someone who doesn't know you came across with this repository. Let them understand what it is about)

- I liked the way you wrote the user stories but try to write them from the perspective of someone who will use your web site, not from your perspective.

**Comment by idogrusoz** [comment]
Let's talk a bit about user stories in the class
