### ISSUE TITLE
Francisco: Week 2, Incremental-Development

### ISSUE THREAD

**Issue by ferrycosv** [HackYourFutureBelgium/class-8#105]
### Inspecting the DOM

* [x] [Read through this site](https://hackyourfuture.be/inspecting-the-dom)
* [x] [And practice studying some HTML/CSS here](https://janke-learning.org/dom-tutor)

### HTML & CSS

* [x] [What is Responsive Design?](https://www.youtube.com/watch?v=5KGah8bW8GE)

### Code Review

* [x] [Take a look through this page from Study](https://study.hackyourfuture.be/programming/code-review)

## Project
This week's project is to study the **app-theme** tutorial from Traversy Media.

* [x] [repository](https://github.com/ferrycosv/app-theme)
* [x] [live](https://ferrycosv.github.io/app-theme/)

### Branches
* [x] [Step 1: Setup the working folder and git](https://github.com/ferrycosv/app-theme/tree/initial-setup-fleboxgrid-conf)
* [x] [Step 2: Creating the header](https://github.com/ferrycosv/app-theme/tree/header-flexboxgrid-layout)
* [x] [Step 3: Creating the showcase area](https://github.com/ferrycosv/app-theme/tree/creating-showcase-area)
* [x] [Step 4: Building features area](https://github.com/ferrycosv/app-theme/tree/features-layout)
* [x] [Step 5: Info area layout](https://github.com/ferrycosv/app-theme/tree/info-section-layout)
* [x] [Step 6: Company contact area and footer](https://github.com/ferrycosv/app-theme/tree/company-contact-footer)
* [x] [Step 7: Company complete about page](https://github.com/ferrycosv/app-theme/tree/about-page)
* [x] [Step 8: Services webpage](https://github.com/ferrycosv/app-theme/tree/services-complete-page)
* [x] [Step 9: Contact page](https://github.com/ferrycosv/app-theme/tree/contact-page-html)
* [x] [Step 10: CSS style for the homepage](https://github.com/ferrycosv/app-theme/tree/index-page-css-style)
* [x] [Step 11: CSS style for the about, services and contact pages](https://github.com/ferrycosv/app-theme/tree/related-pages-ccs-style)

## Exercises

* Sign in to FreeCodeCamp using your GitHub account:
  * [ ] Complete all 4 of FreeCodeCamp's [Responsive Web Design Principles](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/) challenges.
  * [ ] Turn on your public portfolio (if you haven't yet) so we can give feedback on your code
* Fork and Clone [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems) (if you haven't already):
  * [ ] Turn on GitHub Pages
  * [ ] Complete the exercises in `./level-2`
  * [ ] Push your work regularly, so you can ask questions with issues!
* Fork and Clone [css-exercises](https://github.com/dangodev/css-exercises)
  * [ ] Turn on GitHub Pages
  * [ ] Complete `exercise-3`, `exercise-4` and `exercise-5`
  * [ ] Push your work regularly, so you can ask questions with issues!

**Comment by idogrusoz** [comment]
Nice and clean code and very good work!

I don't close the issue yet and ask you to make a google search about how to write user stories. Maybe you can find some inspiration to improve them.

**Comment by ferrycosv** [comment]
Hi @idogrusoz,

Thank you for the feedback, I've made the necessary changes following the examples on how to write user stories I found on the web. If you have more questions please feel free to ask.

Regards,

**Comment by idogrusoz** [comment]
Well done
