### ISSUE TITLE
Rasha Ali: Week 3, Increnmental Development 

### ISSUE THREAD

**Issue by Rashaali84** [HackYourFutureBelgium/class-8#115]
### Prep Work

- [x] Accessibility 
     - [x] ARIA landmark roles
     - [x] Empathy Prompts
- [x] WireFrames
     - [x] What are these things?
     - [x]  Why are these so great?

### Name of Project:

**DuckDuckGo**

- [x] [repository](https://github.com/Rashaali84/duck-duck-clone)
- [x] [live demo](https://rashaali84.github.io/duck-duck-clone/)
- [x] [README.md](https://github.com/Rashaali84/duck-duck-clone/blob/master/README.md)
- [x] [Development Strategy](https://github.com/Rashaali84/duck-duck-clone/blob/master/development-strategy.md)

**Branches**

- [x]  [step 1- create-project-folders](https://github.com/Rashaali84/duck-duck-clone/tree/create-project-folders)
- [x]  [step 2 - add-header-showcase](https://github.com/Rashaali84/duck-duck-clone/tree/add-header-showcase)
- [x]  [step 3 - add-features](https://github.com/Rashaali84/duck-duck-clone/tree/add-features)
- [x]  [step 4 - add-style](https://github.com/Rashaali84/duck-duck-clone/tree/add-style)
- [x]  [step 5 - add-fav-icon](https://github.com/Rashaali84/duck-duck-clone/tree/add-fav-icon)

### Exercises:

- [x] HTML-CSS-Practice-Problems:  ./level-3 :
                     [repo](https://github.com/Rashaali84/HTML-CSS-Practice-Problems/tree/master/level-3)
                     [live](https://rashaali84.github.io/HTML-CSS-Practice-Problems/level-3/)

- [x] css-exercises: exercise-6
                         [repo](https://github.com/Rashaali84/css-exercises/tree/master/exercise-6)
                         [live](https://rashaali84.github.io/css-exercises/exercise-6/)

- [x] css-exercises: exercise-8
                        [repo](https://github.com/Rashaali84/css-exercises/tree/master/exercise-8)
                        [live](https://rashaali84.github.io/css-exercises/exercise-8/)

**Extras :+1:** 

Fork & Clone html-css-git-exercises
                        [repo](https://github.com/Rashaali84/html-css-git-exercises)
                        [live (if there is)](https://rashaali84.github.io/html-css-git-exercises/)

**Comment by idogrusoz** [comment]
First of all sorry for a late review. 
- You did your assignment quickly but not completely.
- I am sure that you can bring your clone much more similar to the original.
- This assignment is about HTML and CSS. You may know/started to learn Javascript but you shouldn't use it here. Keep this in mind and never do more than what is in the issue/user story. That is not being lazy or incompetent. That is planned work.
- I will not close the issue now. If you have time, you can add somethings today. Otherwise, feel free to close the issue and move it to the done section. I leave it up to you.

**Comment by Rashaali84** [comment]
Hello Ibrahim :
   for the main website I do have the following features :
   1- Aria landmark roles .
   2- I checked contrast of colors for accessibility. 
   3- I added info and labels for all tags that needs extra information for accessibility reasons .
   4- My design is responsive, and it is all well displayed on all view ports .
   5- I ran web accessibility fire-fox plugin on the website and made sure that it is all okay .
   6- I add fav-icons for all ports and mobiles types and test the design on different ports .
   7- I finished all needed exercises the all 3 (the required ones ).
   8-  My branches are well structured and clean .
    9- I didn't use java-script code ? as I know it is not required and I don't have any in my solution .
   10- My clone is really a copy of the original , ( although I was told in the lecture that we don't need to have a carbon copy as the original ).
Thank you .

**Comment by idogrusoz** [comment]
I didn't mean to underestimate the work you have done. I am sorry that you took it the way you did and the misunderstanding about the JS. I believe that you are an amazing student in Hack Your Future and you are going to leave a mark behind when you graduate. 
Take care

**Comment by Rashaali84** [comment]
Thank you so much Ibrahim , I was just explaining more , so I can understand how to improve my work , I really appreciate your time and efforts and your continuous help! , Thank you again and have a nice evening .
