### ISSUE TITLE
Francisco: Week 3, Incremental Development

### ISSUE THREAD

**Issue by ferrycosv** [HackYourFutureBelgium/class-8#126]
### Prep Work

- [x] Accessibility 
     - [x] ARIA landmark roles
     - [x] Empathy Prompts
- [x] WireFrames
     - [x] What are these things?
     - [x]  Why are these so great?

### Name of Project:

__DuckDuckGo clone__

- [x] [repository](https://github.com/ferrycosv/duck-duck-clone)
- [x] [live](https://ferrycosv.github.io/duck-duck-clone/)

### Branches
* [x] [Step 1: Layout wireframe](https://github.com/ferrycosv/duck-duck-clone/tree/development-strategy-draft)
* [x] [Step 2: Header and Main Search](https://github.com/ferrycosv/duck-duck-clone/tree/header-main-search)
* [x] [Step 3: Showcase section](https://github.com/ferrycosv/duck-duck-clone/tree/showcase-section)
* [x] [Step 4: Features section](https://github.com/ferrycosv/duck-duck-clone/tree/features-section)
* [x] [Step 5: Info section](https://github.com/ferrycosv/duck-duck-clone/tree/information-sections)

### Exercises

There are 3 sets of exercises to start.

* [ ] In [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems):
  * Turn on GitHub Pages
  * Complete the exercises in `./level-3`
  * Push your work regularly, so you can ask questions with issues!
* [ ] In [css-exercises](https://github.com/dangodev/css-exercises)
  * Turn on GitHub Pages
  * Complete `exercise-6` and `exercise-8`
  * Push your work regularly, so you can ask questions with issues!
* [ ] Fork & Clone [html-css-git-exercises](https://github.com/CodeYourFuture/html-css-git-exercises)
  * Turn on GitHub Pages
  * Begin the exercises.  There is no specific assignment, just a lot more practice available to keep your HTML/CSS sharp throughout the next modules
  * Push your work regularly, so you can ask questions with issues!

**Comment by otagi** [comment]
Good wireframe, development strategy, code, and branches. 👍
