### ISSUE TITLE
mesutBE: Week 1, Question and Solve

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#154]
Hi All,
I have been struggling on a problem and couldn't move any until now. It is 04.02am now... :sleeping: 

![Screenshot from 2020-02-06 04-01-38](https://user-images.githubusercontent.com/59531743/73902243-6761a180-4895-11ea-99af-0d1551ffb502.png)

It is about getting value from input text.

The problem was `var a = parseInt(document.querySelector('#value1').Value);` here...
Can you see any problem?!
I haven't seen until now..

But the problem is about `Value` syntax. And all the time I run the project. It creates UNDEFINED error. I change it with `value`. And all the errors gone. Maybe some of you have same problem and it will help you.

Thank you @ayseakyol because I copied your code and Tried to find the problem, and I caught it.

**Comment by colevandersWands** [comment]
can you push your code and turn on github pages? then we can inspect the live project, this makes it much easier to find your bugs
@MesutBE

**Comment by MesutBE** [comment]
Yeah I pushed it, but you know I solved it in the night 😁 What can I do for help?

**Comment by colevandersWands** [comment]
@MesutBE, it seems to be working. (I did take my time checking it :)  

it looks nice!  if you want to clean it up a bit you can just move the 3 lines reading the dom from `calc` into the top of `calculateHandler` and connect `calculateHandler` in the listener instead

**Comment by colevandersWands** [comment]
@MesutBE.  there's still a couple test cases to pass!  and to clean up your code a bit you move the code from `calc` into the top of `calculateHandler` then connect `calculateHandler` directly into the listener

**Comment by MesutBE** [comment]
Hi @colevandersWands, I updated the code. But I couldn't find any solution for reading user input from (button click) event? Is there any way?
