### ISSUE TITLE
mesutBE: Week 1, DOM element Properties and Methods

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#155]
Hi @colevandersWands ,

I am struggled on the [Fill in the blanks](https://github.com/HackYourFutureBelgium/using-user-input/tree/master/1-fill-in-the-blanks) exercises, at Patches and Selecting Buttons. 

And I see my missing is I don't know which `DOM Element properties` I need to use.

Maybe some of my friends have same struggle.

For example;
```javascript
function identifyButton(event) {
  // read & process user input
  const buttonText = event.target.innerText;

  // execute core logic
  const centerMessage = generateMessage(buttonText);

  // display results to user
  document.getElementById('center-text').innerHTML = centerMessage;

  // log action for developers
  console.log('\n-- identifyButton --');
  console.log('buttonText:', '(' + typeof buttonText + ')', buttonText);
  console.log('centerMessage:', '(' + typeof centerMessage + ')', centerMessage);

  // tell the browser everything is OK
  return true;
}
```

`  const buttonText = event.target.innerText;`

```javascript
function setBackground(event) {
  // read & process user input
  const divId = event.target.id;

  // execute core logic
  const newColor = filterColors(divId);

  // display results to user
  document.body.style.backgroundColor = newColor;

  // log action for developers
  console.log('\n-- setBackground --');
  console.log('divId:', '(' + typeof divId + ')', divId);
  console.log('newColor:', '(' + typeof newColor + ')', newColor);

  // tell the browser everything is OK
  return true;
}
```

`const divId = event.target.id;`

So I attached a link above, that link explains DOM Element properties and methods.

They are all blanks for us in the exercises, so this link could make it easy to understand. 

https://www.w3schools.com/jsref/dom_obj_all.asp

**Comment by colevandersWands** [comment]
@MesutBE, great issue!  this is indeed exactly what you should be learning in this exercise.  

This sunday you'll also see how you can use the debugger to step through and see all DOM object properties as well.  this is also in the `listeners-and-handlers` exercises
