### ISSUE TITLE
mesutBE: Week 2, Variables

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#164]
I couldn't understand the `sum` value of above function. Please explain somebody. 
@greg-hermans, @colevandersWands 

I added 4 logs.
First 2 of them ok. I know why `sum = 0`.
But 3. and 4. logs,` sum is 3 and 8???` I guess they all should be 0.

```Java Script
// Example
let sum = 0;
function addThree() {
  sum = sum + 3;
}
console.log('After Create a function addThree() sum=' + sum);
// Only change code below this line

function addFive() {
  sum = sum + 5;
}
console.log('After Create a function addFive() sum=' + sum);
// Only change code above this line
addThree();
console.log('After calling addThree() sum=' + sum);
addFive();
console.log('After calling addFive() sum=' + sum);
```
This code from FreeCodeCamp JavaScript exercises, you can see orijinal from [here](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-undefined-value-returned-from-a-function).

**Comment by colevandersWands** [comment]
@MesutBE.  this example is showing how calling a function is different from declaring it, and how a function can modify global scope variables.  if you find JS Tutor helpful, then take a look at this snippet in there.  
what you'll see is that calling the functions (`addThree()` and `addFive()`) modify the sum variable declared at the top of the snippet

**Comment by MesutBE** [comment]
Ok @colevandersWands thank you.
