### ISSUE TITLE
mesutBE: Week 3, Question - Debugging and Node.js

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#189]
Hi @greg-hermans and @colevandersWands 

I don't understand if there is a connection between [JavaScript debugger](https://www.youtube.com/watch?v=DsH-fizHkcY) and [Node.js](https://www.youtube.com/watch?v=DsH-fizHkcY)?

I think they are separate topics, but why both are in the same video?

**Comment by colevandersWands** [comment]
@MesutBE 
Node.js is at it's heart just another place you can run JavaScript.  it has many extra super powers (being a web server, file system access, ...) but a node project in it's most basic form is just a javascript file

So saying the debugger in VSC can debug Node.js really means it can debug JavaScript, plus some extra fancy stuff.  But there aren't so many videos I could find that show how to use the VSC JS debugger without running a server as well

**Comment by MesutBE** [comment]
Ok thanks @colevandersWands. I think we will understand better in next weeks.

**Comment by colevandersWands** [comment]
I'm pretty sure you'll figure it out quickly.  You can think of the VSC debugger as just a little different version of the Browser debugger

**Comment by MesutBE** [comment]
It looks a bit confused now. It shows all of the values at the same time. I am more comfortable with browser debugger. But I don't know If it is possible debugging a js file with browser.

**Comment by colevandersWands** [comment]
@MesutBE  it's true the VSC debugger can take a bit longer to get used to.

to edit the exercises in the browser you can create an index.html file in the folder of your exercises, put a `debugger` at the beginning of each exercise, and include each exercise as a script. 
the workflow is then: open index.html in browser -> step through the exercise you're studying -> edit in VSC -> refresh browser & repeat.

Not glamorous but it gets the job done

**Comment by MesutBE** [comment]
@colevandersWands 
Yes, Not glamorous! :smile: 
But thanks for your explanation.

**Comment by greg-hermans** [comment]
Hello. You can also use VS Code to debug without using Node.js. You can follow for example, this article (https://www.digitalocean.com/community/tutorials/debugging-javascript-with-google-chrome-devtools-and-visual-studio-code). At the end, in the section called "Debug in VS Code". All it takes is to install a VS Code extension for your browser type (the article mentions Chrome, but I could easily find one for Firefox and Edge) and create a "launch configuration" that will start a new browser instance and open your index.html file automatically. If you do this, I think the process becomes (slightly) more glamorous: put a breakpoint in VS Code, press F5 to open your page, debug it and modify it all in VS Code. Of course, you still need to refresh the page after each edit.

**Comment by MesutBE** [comment]
Thank you @greg-hermans
