### ISSUE TITLE
mesutBE: Week 3, Question - replace-substring.js

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#191]
Hi @greg-hermans, @colevandersWands 

I couldn't solve the replace-substring.js, I can't pass `Test 6`
```java script
  { name: 'Test 6', args: ['..|..|..', '|.', ','], expected: '..,.,.' },
```
This is my latest update: https://github.com/MesutBE/soc-week-3-project/commit/136cfabba6162ecf102723bc138e47e807f796bf

**Comment by Rashaali84** [comment]
Hello Mesut I used this expression 
// replace every occurrence of a substring with a new value
function replaceSubstring(str, oldThing, newThing) {
  //str.split(search).join(replacement)
  str = str.split(oldThing).join(newThing);
  return str;
}
also this article is really useful , have a look at it :) 
https://dmitripavlutin.com/replace-all-string-occurrences-javascript/

**Comment by MesutBE** [comment]
Thank you @Rashaali84, nice article about my question, and also your solution.
