### ISSUE TITLE
Ayse:  Working with code, week 1

### ISSUE THREAD

**Issue by ayseakyol** [HackYourFutureBelgium/class-8#21]
## My First Homework

- [x] (computer) Software Installations
  - [x] [Chromium](https://download-chromium.appspot.com/), [Firefox](https://www.mozilla.org/en-US/firefox/developer/) or [Brave](https://brave.com/download/): All great browsers with ES6, HTML5 & CSS3 support plus pre-installed, top-knotch developer tools.  Try each one to see what you like best!
  - [x] [Visual Studio Code](https://code.visualstudio.com/download): Like Microsoft Word, but for code ...  and _sooooo_ much better.  After installing VSC, be sure to install these plug-ins:
    - [x] [Markdown Preview Github Styling Custom](https://marketplace.visualstudio.com/items?itemName=dmodalek.markdown-preview-github-styles-custom)
    - [x] [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
    - [x] [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview)
  - [x] [GitKraken](https://www.gitkraken.com/download): A program that will help you master using git.
  - [x] (If you have windows) [Git For Windows](https://gitforwindows.org/): This will allow you to use the same terminal commands & tools as Linux or Mac computers.
- [x] (computer) Start an HYF Directory
- [x] [My bio on the class repo](https://github.com/HackYourFutureBelgium/class-8/blob/master/student-bios/ayseakyol.md)
- [x] [Hack My Future](https://github.com/ayseakyol/hack-my-future)
- [x] [Markdown Home Page](https://github.com/ayseakyol/ayseakyol.github.io) - my multi-page markdown home portfolio, live on github pages

**Comment by colevandersWands** [comment]
Well Done!  Time to [prepare for Sunday](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-1#prep-work) :)

**Comment by ayseakyol** [comment]
Thank you :relaxed: 
:unicorn:
