### ISSUE TITLE
mesutBE: Week 2, js-exercises-tdd => 9, 10 and 11 fails

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#224]
Hi @KevinTss, @colevandersWands,
I don't understand what we should code at the exercises => 9, 10 and 11.
Please help me.
https://github.com/CodeYourFuture/js-exercises-tdd/pull/60/files

**Comment by KevinTss** [comment]
Hey @MesutBE 

- For the ex 9 you need to create the `sales()` function: https://github.com/CodeYourFuture/js-exercises-tdd/blob/master/I.pass-tests/09-car-sales/car-sales.test.js#L21
which is suppose to return the `total` object

- For the 10,  you need to create a function who will return a new array containing the painted car base on the colour that you pass.

-  End for the 11, you need to create `formatCities` which suppose to receive an array of capitals & countries, and as a second parameters, a callback function to be executed on each element. Then you should return the output array

Is that explanation helps you?

**Comment by MesutBE** [comment]
Thank you @KevinTss,
For ex 9, now I get the idea after clearing my mind :)
For ex 10 I code it but I couldn't pass
For ex 11 I am still trying to understand :)

**Comment by MesutBE** [comment]
@KevinTss  I passed all now.
