### ISSUE TITLE
mesutBE: Week 3, about js-tdd II.write-tests

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#229]
Hi @KevinTss, @colevandersWands,
Don't you think something wrong with this => ex II.write-tests.
I think this doesn't not help us to think what is expected to return when we read function name.
For example..
It says remove vowels;
You need to write test to be passed as that expected results,
`var expected = "_a_ue_";`
see my code please;
https://github.com/CodeYourFuture/js-exercises-tdd/pull/61/commits/eb428792ae3b03394e95b17850c293fe5724f4c3

**Comment by colevandersWands** [comment]
it is a bit of a confusing name, i guess they mean for it to "remove vowels" as in for later use somewhere else?  but then an array would make more sense as a return value.
otherwise it would be more natural to replace vowels with _ instead of the consonants.

PR?
