### ISSUE TITLE
mesutBE: Week 3, janke tdd exercises "merge-arrays-saved"

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#238]
Hi @colevandersWands, @bramdevries,
I am blocked in this exercise; at the `merge-arrays-saved` tab.
http://janke-learning.org/tdd/?exercise=exercises%2Fobjects-101%2Fmeta

My solution is that,

```javascript
const obj = {
  array: [3],
  mergeArrays: function (arrToMerge) { 
    obj.array = [...obj.array, ...arrToMerge];
    return obj.array;
  }
}
```

**Comment by colevandersWands** [comment]
you're failing the test that ask for you to avoid side-effects.  your method is modifying the .array property when it shouldn't be

**Comment by MesutBE** [comment]
@colevandersWands, unfortunately JS Tutor tells me I am not failing. But I think the key is `side-effects`, Ok, I will find the missing point.

**Comment by colevandersWands** [comment]
did you copy the test cases into js tutor as well?

its the test cases that are enforcing the side-effects

**Comment by MesutBE** [comment]
No, not. And I couldn't find good explanation about side effects.
When I write my code. It always give result as [3,2,2], but I don't push it twice? @colevandersWands

**Comment by colevandersWands** [comment]
side effects is related to what kevin talked about with reference vs. value.  there are some examples/exercises here: https://hackyourfuture.be/state/week-1/#/side-effects-code

**Comment by MesutBE** [comment]
```javascript
const obj = {
  array: [3],
  mergeArrays: function (arrToMerge) {
    }
}

describe(`the method merges with the array property`, () => {
  it('the new argument goes at the end', () => {
    obj.mergeArrays([2]);
    assert.deepStrictEqual(obj.array, [3, 2])
  });
  it('and does modify the array property', () => {
    obj.mergeArrays(obj.array);
    assert.deepStrictEqual(obj.array, [3, 2, 3, 2])
  });
  it('the new argument still goes at the end', () => {
    obj.array = [5]
    obj.mergeArrays([1]);
    assert.deepStrictEqual(obj.array, [5, 1])
  });
  it('and still modifies the array property', () => {
    obj.mergeArrays([-5]);
    assert.deepStrictEqual(obj.array, [5, 1, -5])
  });
});
```
But @colevandersWands, at the 2nd assert, it says  'and does modify the array property'
This is a side effect, isn't it?
Can you pass the asserts :)? I really tried all I know.

>>>how can you get the correct return value without modifying the stored array?
Your answer I think:
```javascript
const obj = {
  array: [3],
  mergeArrays: function (arrToMerge) {
    return [...obj.array, ...arrToMerge];
    }
}
```

**Comment by colevandersWands** [comment]
you are right, I misread your question and was talking about the wrong problem.  and the solution you shared with [...obj.array, ...arrToMerge] is what i had in mind for the wrong problem

when I copy your solution for the "modify" problem into the site and run the tests, they pass

**Comment by MesutBE** [comment]
https://github.com/janke-learning/tdd/issues/3
