### ISSUE TITLE
Mesut, Work with Code, Week 1

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#24]
## My First Homework

- [x] (computer) Software Installations
  - [x] [Chromium](https://download-chromium.appspot.com/), [Firefox](https://www.mozilla.org/en-US/firefox/developer/) or [Brave](https://brave.com/download/): All great browsers with ES6, HTML5 & CSS3 support plus pre-installed, top-knotch developer tools.  Try each one to see what you like best!
  - [x] [Visual Studio Code](https://code.visualstudio.com/download): Like Microsoft Word, but for code ...  and _sooooo_ much better.  After installing VSC, be sure to install these plug-ins:
    - [x] [Markdown Preview Github Styling Custom](https://marketplace.visualstudio.com/items?itemName=dmodalek.markdown-preview-github-styles-custom)
    - [x] [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
    - [x] [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview)
  - [x] [GitKraken](https://www.gitkraken.com/download): A program that will help you master using git.
  - [x] (If you have windows) [Git For Windows](https://gitforwindows.org/): This will allow you to use the same terminal commands & tools as Linux or Mac computers.
- [x] (computer) Start an HYF Directory
- [x] [My bio on the class repo](https://github.com/hackyourfuturebelgium/class-8/blob/master/student-bios/MesutBE.md)
- [x] [Hack My Future](https://github.com/MesutBE/hack-my-future)
- [x] [Markdown Home Page](https://github.com/mesutbe/mesutbe.github.io) - my multi-page markdown home portfolio, live on github pages

**Comment by colevandersWands** [comment]
Still a bit to go:
* You'll need to send a pull request to this repository to complete the bio assignemnt
* In your Hack My Future repo, you still have to set up the project board
* And for your home page, can you add some more text, a link to your github accoutn, and an image?  Right now it won't help others get to know you

**Comment by MesutBE** [comment]
> Still a bit to go:
> 
>     * You'll need to send a pull request to this repository to complete the bio assignemnt
> 
>     * In your Hack My Future repo, you still have to set up the project board
> 
>     * And for your home page, can you add some more text, a link to your github accoutn, and an image?  Right now it won't help others get to know you

>     * Actually I send the pull request but I cannot find it now, I will try again,

>     * I made my project board on my root github page, mistakely,

>     * I am trying to solve gitKraken pushing news to github, I made it once with unwitting.

>     * I will do them..

**Comment by colevandersWands** [comment]
`DONE` !

And I see now that you'd made your project board on your main account.  Feridun had also done that, and it actually makes more sense than putting the project board in the repository since it easier to get to.  
It was something I hadn't thought about before you guys did it.  If you prefer to use the one on your main account go for it!  And my appologies for this confusion. 

🦄
