### ISSUE TITLE
mesutBE: Week 1, encapsulation

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#245]
# Encapsulation, Week 1

### Object Methods: `this`

- [x] [What is Object Oriented Programming? (1)](https://www.youtube.com/watch?v=rlLuL3jYLvA)
- [x] [What is Object Oriented Programming? (2)](https://www.youtube.com/watch?v=CXnnw9rQH5I)
- [x] [javascript.info](https://javascript.info/object-methods)

#### Isolating JavaScript

- [x] Fork [functions-to-methods](https://github.com/MesutBE/functions-to-methods/blob/master/challenges/REVIEW.md)
  - [x] :heavy_check_mark: solve each one :x: on a separate branch and merge to master when they are complete
    [repo](https://github.com/MesutBE/functions-to-methods/blob/master/challenges/REVIEW.md)
- [x] Fork [numbery-organizer](https://github.com/hackyourfuturebelgium/numbery-organizer)
  - [x] solve each one on a separate branch and merge to master when they are complete
    [live](https://mesutbe.github.io/numbery-organizer/)
- [x] Fork [getters-and-setters](https://github.com/hackyourfuturebelgium/getters-and-setters)
  - [x] solve each one on a separate branch and merge to master when they are complete
    [repo](https://github.com/MesutBE/getters-and-setters/blob/master/REVIEW.md)

#### Integrating JavaScript

- [x] Form a group of 2-3 and Complete 1 [JavaScript 30](https://github.com/hackyourfuturebelgium/javascript-30) group challenge, your choice!
  - [x] [Sort Without Article - Repo ](https://github.com/Rashaali84/Sort-Without-Articles)
  - [x] [Sort Without Article - Live](https://rashaali84.github.io/Sort-Without-Articles/)

#### Challenge Exercises

- (_Isolate_) Begin [FCC Functional Programming](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/)
- (_Isolate_) Begin [FCC Intermediate Algorithm Scripting](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/)
- (_Isolate_) Fork [javascript-exercises](https://github.com/TheOdinProject/javascript-exercises)
- (_Isolate_) Keep learning about TDD: [what is TDD?](https://duckduckgo.com/?q=what+is+tdd%3F&iax=videos&ia=videos)

### Project: `practical-javascript`
- [repo](https://github.com/MesutBE/practical-javascript)
- [live](https://mesutbe.github.io/practical-javascript/)
- [x] Write a complete [README](https://github.com/MesutBE/practical-javascript/tree/master) describing your project and what you learned.
- [x] Make sure each step of the tutorial is on a separate branch.
  1. [Branch - v1](https://github.com/MesutBE/practical-javascript/tree/v1)
  1. [Branch - v2](https://github.com/MesutBE/practical-javascript/tree/v2)
  1. [Branch - v3](https://github.com/MesutBE/practical-javascript/tree/v3)
  1. [Branch - v4](https://github.com/MesutBE/practical-javascript/tree/v4)
  1. [Branch - v5](https://github.com/MesutBE/practical-javascript/tree/v5)
  1. [Branch - v6](https://github.com/MesutBE/practical-javascript/tree/v6)
  1. [Branch - v7](https://github.com/MesutBE/practical-javascript/tree/v7)
  1. [Branch - v8](https://github.com/MesutBE/practical-javascript/tree/v8)
  1. [Branch - v9](https://github.com/MesutBE/practical-javascript/tree/v9)
  1. [Branch - v10](https://github.com/MesutBE/practical-javascript/tree/v10)
  1. [Branch - v11](https://github.com/MesutBE/practical-javascript/tree/v11)
  1. [Branch - v12](https://github.com/MesutBE/practical-javascript)
- [x] Refactor your code from the final version of the project (1 file) into separate folders & files as you learned in class, this should be on the master branch.
- [x] Write a `development-strategy.md` file to explain the steps Gordon used to develop the project in this tutorial

You will be assessed not only on your live demo, but also on the quality of your code, the correctness of your branches, the organization of your code, and the completeness of your README.

[~comments]: https://img.shields.io/badge/-continues-blue

### Tips & Triks & Useful pages

https://shields.io/
https://medium.com/complete-coding/become-a-developer-and-get-your-first-job-fast-7b8ac26d84c6
https://dev.to/bhuvanaguna/css-only-image-beginner-4ghj

---
---

### <a href="https://hackyourfuture.be" target="_blank"><img src="https://user-images.githubusercontent.com/18554853/63941625-4c7c3d00-ca6c-11e9-9a76-8d5e3632fe70.jpg" width="100" height="100" alt="Hack Your Future: Belgium"></a>

**Comment by bramdevries** [comment]
**numbery-organizer**

- I like that you used early returns in the `addString` and `isNumberyString` methods. One benefit of using them is that in most cases it means the `else` condition is not needed, so your `addString` method could also be:

```js
if (typeof param !== 'string') { return false; }

if (isNaN(param)) {
	this.NaNyStrings.push(param);
	return true;
}

this.numberyStrings.push(param);
return true;
```

- It's possible to re-use an objects methods in other methods, so your `sumOf*` methods could use the `*AsNumber` methods. This means your logic to cast the value to it's numeric value can be kept in a single place

```js
return this.NaNyAsNumbers().reduce((total, num) => {
  return total + num;
}, 0);
```

---

**getters-and-setters**

- Try to write getters and setters in lowercase, eg: `set currentEntry`. This is a very minor thing but it's a good convention.

---

**Project: practical-javascript**


- I'm missing the development strategy. Try to always write down the steps you're going to take, it can act as a reference for the features you're going to build within your program. Writing it out upfront doesn't mean you cannot change it at a later point.
- You focussed a lot on how the todos are managed in the object, but I miss the visual side of things (there's also no live version). What are the things you would change if you were to add an interface to this project to manage the todos?

**Comment by MesutBE** [comment]
Hi @bramdevries, thank you your review and detailed feedback,

> **numbery-organizer**
> 
>     * I like that you used early returns in the `addString` and `isNumberyString` methods. One benefit of using them is that in most cases it means the `else` condition is not needed, so your `addString` method could also be:
> 
> 
> ```js
> if (typeof param !== 'string') { return false; }
> 
> if (isNaN(param)) {
> 	this.NaNyStrings.push(param);
> 	return true;
> }
> 
> this.numberyStrings.push(param);
> return true;
> ```

:heavy_check_mark: I fixed this.

>     * It's possible to re-use an objects methods in other methods, so your `sumOf*` methods could use the `*AsNumber` methods. This means your logic to cast the value to it's numeric value can be kept in a single place
> 
> 
> ```js
> return this.NaNyAsNumbers().reduce((total, num) => {
>   return total + num;
> }, 0);
> ```

:heavy_check_mark: I fixed this.

> **getters-and-setters**
> 
>     * Try to write getters and setters in lowercase, eg: `set currentEntry`. This is a very minor thing but it's a good convention.

I remember at the freecodecamp exercises that functions in objects (they are called methods) they tell '`use uppercase when give a name to methods`', so I thought getters and setters are the same. I changed it.
:heavy_check_mark: I fixed a lot of this.

the code below has a bug. I know how can I fix it but:

how can we realize that object item is an value or method?

when I write `obj2.module = 2`
I don't know if it is a value or method?

```javascript
const obj2 = {
  numbers: [12, 4, 9, 36],
  mods: [],
  modulo: 3,
  set modulo(newModulo) {
    this.modulo = newModulo;
    this.mods = this.numbers.map(x => x % this.modulo);
  }
}
``` 

> **Project: practical-javascript**
> 
>     * I'm missing the development strategy. Try to always write down the steps you're going to take, it can act as a reference for the features you're going to build within your program. Writing it out upfront doesn't mean you cannot change it at a later point.
> 
>     * You focussed a lot on how the todos are managed in the object, but I miss the visual side of things (there's also no live version). What are the things you would change if you were to add an interface to this project to manage the todos?

I am coming to end of the versions (`there are 11 versions must be done`). At the end, mine will be v12 and I will refactor them all to what we have learnt.

**Comment by bramdevries** [comment]
> how can we realize that object item is an value or method?
> when I write obj2.module = 2
> I don't know if it is a value or method?

That's a valid concern. In the examples you'll see that the actual value is stored in `this._modulo` so you're setter will not call itself. However with this approach you'd still be able to access the `obj2._module` property without using it's getter.

There's some interesting lecture that explores the different ways you can use private properties within an object: https://css-tricks.com/implementing-private-variables-in-javascript/

**Comment by bramdevries** [comment]
Nice. I like how you split up the responsibilities between the view and TodoList objects.

---

One suggestions that will help simplify some code in `Todolist` is to make use of  javascript's native array methods to get the total number of completed todos:

```js
var completedTodos = this.todos.filter(todo => todo.completed).length;
```
