### ISSUE TITLE
mesutBE: Week 3,  Question => es6 exercises, ch4

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#271]
Hi @colevandersWands, @bramdevries,
Challenge 4 in es6 exercise, what is the best way to pass this test cases? Sorting initial values or whole values after adding new value doesn't return the right results.
Test 4.A - initial values
Test 8.A - new values
https://github.com/MesutBE/es6-classes/blob/master/literals-to-class/challenge-4.js#L112
https://github.com/MesutBE/es6-classes/blob/master/literals-to-class/challenge-4.js#L140
```javascript
const instanceA = new Stringanizer(['3', '', 'e', '2']);

const test4a = JSON.stringify(instanceA.state) === '{"evens":["2",""],"odds":["3"],"nanys":["e"]}';

instanceA.addString('12');

const test8a = JSON.stringify(instanceA.state) === '{"evens":["2","","12"],"odds":["3","1"],"nanys":["e","*"]}';
```

This is my solution:
```javascript
addString(newStr) {
    if (typeof newStr !== 'string') { return false; }

    if (!isNaN(newStr)) {
      if (newStr % 2 === 0) {
        this.state.evens.push(newStr);
        if (this.state.evens.includes('')) {
          this.state.evens.splice(this.state.evens.indexOf(''),1);
          this.state.evens.splice(1, 0, '');
        }
      } else {
        this.state.odds.push(newStr);
      }
    } else {
      this.state.nanys.push(newStr);
    }
  }
```

And can you give us the solutions for the es6 exercises, I want to see the best and ideal solutions for them, spatially building constructors.

**Comment by bramdevries** [comment]
To be honest (but I'll let @colevandersWands confirm this) it looks like a mistake in the initialization of `instanceA`. If you change it to the following the tests will pass without needing to add any sorting.

```js
const instanceA = new Stringanizer(['3', 'e', '2', '']);
```

**Comment by bramdevries** [comment]
As for the solution, your looks quite good. I would prefer using early returns in `addString` as it reads easier:

```js
if (typeof value !== 'string') {
  return;
}

if (Number.isNaN(Number(value))) {
  this.state.nanys.push(value);
  return;
}

if (value % 2 === 0) {
  this.state.evens.push(value);
  return;
}

this.state.odds.push(value);
```

You also don't have to make the `all` method too complex, you can access the values in `state` like this:

```js
return this.state[key] || [];
```

Your constructor is looking quite good, a small optimization you can make (to remove the anonymous function) is to use `values.forEach` in combination with a bound function:

```js
values.forEach(this.addString.bind(this));
```

**Comment by colevandersWands** [comment]
> To be honest (but I'll let @colevandersWands confirm this) it looks like a mistake in the initialization of `instanceA`. If you change it to the following the tests will pass without needing to add any sorting.
> 
> ```js
> const instanceA = new Stringanizer(['3', 'e', '2', '']);
> ```

True thing, it was a mistake in the test.  I've updated the repo and will share on Slack
