### ISSUE TITLE
ThomasHaile: Week1, Personal

### ISSUE THREAD

**Issue by thomashaile** [HackYourFutureBelgium/class-8#272]
### Name of Project:

- [repository](github.com/thomashaile/covid19tool/)
- [live demo](https://thomashaile.github.io/covid19tool/index.html)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by colevandersWands** [comment]
@thomashaile, what do you need help with?
