### ISSUE TITLE
mesutBE, Question, CORS policy 

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#292]
Hi @KevinTss, @colevandersWands,

I have an error screen captured below (it is **`solution.html`**)

How can I solve it? _I have already read your attention, but couldn't solve._ What will be the permision when we **`generating an access token`**?
>>We're going to use the fetch function to get a user from the GitHub API. The API is free to access, but you might get rate-limited if you make too many requests. We can avoid this by generating an access token and including it in our request URL.

![Screenshot from 2020-04-21 16-12-47](https://user-images.githubusercontent.com/59531743/79876574-83340880-83eb-11ea-8024-57a7cd6d6b2a.png)

**Comment by Rashaali84** [comment]
hello @MesutBE  , May I suggest this link ..
https://dev.to/gr2m/github-api-authentication-personal-access-tokens-53kd

**Comment by MesutBE** [comment]
Thanks @Rashaali84, answer seems; choose only **`public_repo`**, for now it is enough.
