### ISSUE TITLE
Alejandro: week 2, Web apps

### ISSUE THREAD

**Issue by AlejoVE** [HackYourFutureBelgium/class-8#338]
Hi! I have a problem running the front-end of the app. After putting the command `npm run start` (inside the client folder) I receive the following message:

![error1](https://user-images.githubusercontent.com/59319966/81936877-20e9b480-95f3-11ea-9b38-d00385218444.png)

And this is what I see in the browser: 
![error-browser](https://user-images.githubusercontent.com/59319966/81936959-3bbc2900-95f3-11ea-9db3-c8bc2a58f970.png)

After reading a bit I saw that the problem seems to be due to a bug in the react-script version and that it is corrected in version 3.4.0, so I ran the command `npm install --save-dev --save-exact react-scripts@3.4.0` to update the script .

After that the problem seems to have been fixed, I can see the homepage in my browser 
with some errors

![error3](https://user-images.githubusercontent.com/59319966/81940819-4b8a3c00-95f8-11ea-9411-aabb589baa24.png)

I don't know if the server is well configured, I can't see anything else on the page, I don't understand what to do from there.

**Comment by samicey** [comment]
Hello @AlejoVE are you still having this problem or has it been resolved?
