### ISSUE TITLE
Alejandro, week 2, web apps

### ISSUE THREAD

**Issue by AlejoVE** [HackYourFutureBelgium/class-8#341]
Hi! I am getting this error when I make a get request to the path  /api /pages/all. 

![error-browser](https://user-images.githubusercontent.com/59319966/82088343-def36800-96f1-11ea-9a24-cf21693d671b.png)

In postman I receive the correct response.

![postman-response](https://user-images.githubusercontent.com/59319966/82088364-e87cd000-96f1-11ea-81c7-2431f219f493.png)

My code :
```
app.get('/api/pages/all', async (req, res) => {
  try {
    const pages = await readDirPromise(DATA_DIR, 'utf-8');
    let list = pages.map((page) => page.replace('.md', ''));
    console.log(list);
    res.send({ status: 'ok', body: list });
  } catch (err) {
    jsonError(err, 'Error loading the page');
  }
});
```

How can I fix this?   

Direct link to the code [here](https://github.com/AlejoVE/diy-wiki/blob/route-get-pages-all/server.js)

**Comment by MesutBE** [comment]
Hi @AlejoVE,
At the first sight, 
Your response needs revision. `http://localhost:3000api/pages/all`
// success response: {status:'ok', **pages**: ['fileName', 'otherFileName']}

your is
// success response: {status:'ok', **body:** ['fileName', 'otherFileName']}

**Comment by AlejoVE** [comment]
@MesutBE Thank you very much for your help, I already fixed the error 👍
