### ISSUE TITLE
mesutBE: Week 1, databases

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#368]
# Databases

[Main Page](https://github.com/HackYourFutureBelgium/databases/tree/master/README.md) | [Week 2 >>](https://github.com/HackYourFutureBelgium/databases/tree/master/week-2/README.md)

## Learning Objectives

- Familiarize some theoretical concepts: information systems, databases, RDMBs, relational models, tables, records, attributes, fields and keys
- Learn how to navigate a (SQLite) database
- Learn how to write basic SQL queries using following statements: `SELECT`, `ORDER BY`, `WHERE`, `GROUP BY` and more
- Learn how to communicate with SQLite databases in JavaScript

---

### Isolate
:heavy_check_mark: Check out this week's exercises [here](https://github.com/HackYourFutureBelgium/databases/tree/master/isolate/week-1/EXERCISES.md).  You can study them in the [SQLite Tutorial Sandbox](https://www.sqlitetutorial.net/tryit/).

### Integrate

You will be learning to use [sqlite3](https://github.com/mapbox/node-sqlite3/wiki/API), a module that allows you to query your SQLite database file.

- [x] [CLI Query Scripts](https://github.com/HackYourFutureBelgium/databases/tree/master/integrate/cli-query-scripts)
   - [x] [solutions](https://github.com/MesutBE/databases/commit/cd0766da48e1a863f47f02d5b5520a566b107147)

---
---

## Assignments

> After Sunday Class

#### SQL

- [x] [sqlteaching](https://www.sqlteaching.com/)
- [x] [SQL Murder Mystery](https://mystery.knightlab.com/)

#### Tooling

- [x] [TablePlus](https://tableplus.com/) is a modern, native, and friendly GUI tool for several relational databases: SQLite, MySQL, PostgreSQL & more.
- [x] [DB Browser for SQLite](https://sqlitebrowser.org/) is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite.
- [x] [SQLite Viewer](https://inloop.github.io/sqlite-viewer/) is an online SQLite editor.
- [x] [SQLite Editor by SQLite Tutorial](https://www.sqlitetutorial.net/tryit/) is also an online SQLite editor, specifically for the Chinook sample database.
- [x] [vscode-sqlite](https://marketplace.visualstudio.com/items?itemName=alexcvzz.vscode-sqlite) is a VSCode extension to explore and query SQLite databases.

#### SQLite & Node.js

- [x] [SQLite Node.js Guide](https://www.sqlitetutorial.net/sqlite-nodejs/)
- [x] [node-sqlite3 has good docs](https://github.com/mapbox/node-sqlite3/wiki/)
- [x] [developerhowto tutorial article](https://developerhowto.com/2018/12/29/build-a-rest-api-with-node-js-and-express-js/)
- [x] PetsApp: [video tutorial (SQLite starts at #7)](https://www.youtube.com/watch?v=2PCaD0Y4MP4&list=PLzV58Zm8FuBIWu1zvGRUfn0Xh6HXRg9cG&index=7), [starter code & finished to study](https://github.com/pgbovine/COGS121)

---

### Exercises

- [ ] :egg: [Chinook Queries](https://github.com/HackYourFutureBelgium/chinook-queries)

---

#### Checklist

- [x] [repo](https://github.com/MesutBE/restful-chinook)
- [x] [live demo](https://restful-chinook.herokuapp.com/)
- [x] A `development-strategy.md`
- [x] One branch per step in your `development-strategy.md`
  - [Branch - albums](https://github.com/MesutBE/restful-chinook/commit/49c57c4bf0e899feec70b66476544dd03707e455)
  - [Branch - artists](https://github.com/MesutBE/restful-chinook/commit/f5c25529488142b62151b4b192812418e62aa0e3)
  - [Branch - genres](https://github.com/MesutBE/restful-chinook/commit/60458373cad54bcc5de8c1a319e6acf4c2656a9a)
  - [Branch - media-types](https://github.com/MesutBE/restful-chinook/commit/2235a703ab69eb4e82d8e91255f9edd170901e96)
  - [Branch - playlists](https://github.com/MesutBE/restful-chinook/commit/e6250da26db8d4ef1457e0e472b8cc379258fbaf)
  - [Branch - tracks](https://github.com/MesutBE/restful-chinook/commit/ffa7e4b610d7d58d72b6196d233da6f9ed3a328b)
  - [Branch - readme](https://github.com/MesutBE/restful-chinook/commit/ffa7e4b610d7d58d72b6196d233da6f9ed3a328b)
- [x] A complete README.md
- [x] A working API in the `/api` directory
- [x] (challenge) A frontend for you API in the `/client` folder

#### `restful-chinook`

Build a RESTful API with CRUD access to all of the musical tables in the `chinook.sqlite` database. Starting with the [restful-chinook](https://github.com/HackYourFutureBelgium/restful-chinook), fill in the controller files in `/api` to create a fully-functioning API.

If you have finished the API and are looking for a challenge, write a frontend!  No suggestions from us, impress yourself :)

#### Deployment

This is a nice first project to try out fullstack deployment.

__Directly from GitHub__

- [FCC Article](https://www.freecodecamp.org/news/how-to-deploy-a-nodejs-app-to-heroku-from-github-without-installing-heroku-on-your-machine-433bec770efe/)
- [Heroku CI](https://www.heroku.com/continuous-integration)

__From Terminal__

- [Heroku Getting Started](https://devcenter.heroku.com/articles/getting-started-with-nodejs)
- [Scotch Tutorial](https://scotch.io/tutorials/how-to-deploy-a-node-js-app-to-heroku)
- [Heroku devhints](https://devhints.io/heroku)
- [Heroku DevCenter: Node.js Support](https://devcenter.heroku.com/articles/nodejs-support)
- [Heroku DevCenter: Advanced Automation](https://devcenter.heroku.com/articles/multiple-environments#advanced-linking-local-branches-to-remote-apps)

**Comment by samicey** [comment]
Hello @MesutBE . You did a good job. Keep up the good work

**Comment by MesutBE** [comment]
Thank you @samicey
