### ISSUE TITLE
Mesut: Week 1, incremental-development

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#74]
### Prep Work

- [x] [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV) - watch through 1.4
- [x] [LearnGitBranching](https://learngitbranching.js.org/) & [video tutorial](https://www.youtube.com/watch?v=dG0ke9vILQM) - complete the first set of exercises
- [x] [Familiarize yourself with GitKraken](https://support.gitkraken.com/start-here/interface/)
- [x] [Study this example project](https://github.com/hackyourfuturebelgium/built-with-branches)
- [x] [Understand how to use Atomic Commits](https://curiousprogrammer.io/blog/how-to-craft-your-changes-into-small-atomic-commits-using-git)

### Name of Project: Acme Web Design
- [x] [repository](https://github.com/MesutBE/acme-web-design)
- [x]  [live demo](https://mesutbe.github.io/acme-web-design)
  - [x]  [MainArea](https://github.com/MesutBE/acme-web-design/commit/779d7a3e7f9a17a7daa50f135575184b7039fb40)
  - [x]  [NewsletterSection](https://github.com/MesutBE/acme-web-design/commit/8934f3ba14299de4d01a3d46cfba0efe167f94b0)
  - [x]  [BuildingNewsletter-2](https://github.com/MesutBE/acme-web-design/commit/250c01b713afc1ed3607f74e03502f6afdf99647)
  - [x]  [BuildingFooter](https://github.com/MesutBE/acme-web-design/commit/d8cd2e1a8b88651792bcb2d7bc971990f31ae116)
  - [x]  [CustomizingStyleCSS-1](https://github.com/MesutBE/acme-web-design/commit/a8f11904aa076e2a4a3bed9d32bb797b3a196087)
  - [x]  [CustomizingStyleCSS-2](https://github.com/MesutBE/acme-web-design/commit/ceec9fd60bd093047d162e4f732bcee2f6758756)
  - [x]  [CustomizingStyleCSS-3](https://github.com/MesutBE/acme-web-design/commit/d2f705a5d40d707bf03299f199015239f7b51d21)
  - [x]  [CustomizingStyleCSS-4](https://github.com/MesutBE/acme-web-design/commit/898859c00bfd0bff98be67ac60d2460530c29242)
  - [x]  [CustomizingStyleCSS-5](https://github.com/MesutBE/acme-web-design/commit/712246b25b9d1b39b51fdb2b09db9037313e7169)
  - [x]  [AboutHTML-1](https://github.com/MesutBE/acme-web-design/commit/94003aafe3fd51a0c3387049ad21442244d8f34d)
  - [x]  [AboutHTML-2](https://github.com/MesutBE/acme-web-design/commit/9a60d1eeae84229b48dfd43c530bd71dd1cace97)
  - [x]  [AboutHTML-3](https://github.com/MesutBE/acme-web-design/commit/63431e505b8a5014ccde06a264090b33eaac8249)
  - [x]  [AboutHTML-4](https://github.com/MesutBE/acme-web-design/commit/34f874fd7e0227a3b61eec89067216dfcf15d6aa)

### Exercises:
- [x] Started the exercises...
- [x] Sign in to FreeCodeCamp using your GitHub account:
  - [x] Complete all 22 of FreeCodeCamp's [Applied Accessibility](https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/) challenges.
  - [x] Turn on your public portfolio so we can give feedback on your code. [live](https://www.freecodecamp.org/mesutbe) 
- [x] Fork and Clone [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems):
  - [x] Turn on GitHub Pages
  - [x] Complete the exercises in `./level-1`
  - [x] Push your work regularly, so you can ask questions with issues!
- [ ] Fork and Clone [css-exercises](https://github.com/dangodev/css-exercises)
  - [ ] Turn on GitHub Pages
  - [ ] Complete `exercise-1` and `exercise-2`
  - [ ] Push your work regularly, so you can ask questions with issues!

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by MesutBE** [comment]
update for well-done issue..

**Comment by MesutBE** [comment]
I created the index.html file and the others, but I cannot reach the live demo. And couldn't find a solution.

I made also steps but I cloged here..

[repository](https://github.com/MesutBE/acme-web-design)
[live demo](https://mesutbe.github.io/acme-web-design)

**Comment by Rashaali84** [comment]
![image](https://user-images.githubusercontent.com/30797974/72529839-5f05e000-386e-11ea-9534-d46af7e4bc8b.png)


Do you modify your settings like the picture ?

**Comment by MesutBE** [comment]
That's the answer big thanks @Rashaali84
