### ISSUE TITLE
ThomasHaile: week 1 - incremental development

### ISSUE THREAD

**Issue by thomashaile** [HackYourFutureBelgium/class-8#75]
### Prep Work

- [x]     git & github for poets - watch through 1.4
- [x]     Learn Git Branching & video tutorial - complete the first set of exercises 
- [x]     Familiarize yourself with GitKraken
- [x]     Study this example project (Built with Branches )
- [x]     Understand how to use Atomic Commits
- [x]     User Stories Agile Development by Cartoon
- [x]     User Stories: Splitting User Stories
- [x]     User Stories: The "what" not the "how"
- [x]     relative vs. absolute paths
- [x]    Internet: How the Internet Works in 5 Minutes
- [x]    Internet: How do Web Browsers Work?
- [x]     Code Review: Take a look through this page from Study

#### Code-Along

- [repository](https://github.com/thomashaile/acme-web-design)
- [live demo](https://user-name.github.io/repo-name)
- [x]  [step 1](https://github.com/thomashaile/acme-web-design/tree/step1creating-simple-default-home-(index)-page)
- [x]  [step 2](https://github.com/thomashaile/acme-web-design/tree/step2-creating-simple-index-page(with-header-and-footer))
- [x]  [step 3](https://github.com/thomashaile/acme-web-design/tree/step3-creating-simple-index-page(adding-showcase%2C-newsletter%2C-the-boxes-container))
- [x]  [step 4](https://github.com/thomashaile/acme-web-design/tree/step4-creating-the-css(css/style.css))
- [x]  [step 5](https://github.com/thomashaile/acme-web-design/tree/step5-creating-inner-pages-(about.html-and-services.html))
- [x]  [step 6](https://github.com/thomashaile/acme-web-design/tree/step6--updating-about.html-inner-page-contents)
- [x]  [step 7](https://github.com/thomashaile/acme-web-design/tree/step7--updating-services.html-inner-page-contents)
- [x]  [step 8](https://github.com/thomashaile/acme-web-design/tree/step8---creating-and-updating-development-startegy-file)
- [x]  [step 9](https://github.com/thomashaile/acme-web-design/tree/step9--update-the-README-file)

### Exercises:

- [x] Sign in to FreeCodeCamp using your GitHub account:
Complete all 22 of FreeCodeCamp's Applied Accessibility challenges(https://www.freecodecamp.org/thomashaile), [live (if there is)]()
- [x] Fork and Clone HTML-CSS-Practice-Problems: [repo](https://github.com/thomashaile/HTML-CSS-Practice-Problems), [live-demo](https://thomashaile.github.io/HTML-CSS-Practice-Problems/level-1/)
- [x] Fork and Clone css-exercises
- [x] Turn on GitHub Pages
- [x] Complete exercise-1 [Exercise-1-live-demo](https://thomashaile.github.io/css-exercises/exercise-1/)and exercise-2 [Exercise-2-live-demo]()

**Comment by idogrusoz** [comment]
- The live demo link doesn't work.
- The development strategy should be according to the example and how you saw it in the class.

I am closing the issue so that you can move on to the next week's work but please consider my remarks here for week 2 assignment.
