### ISSUE TITLE
KLisabeth: Week 1, incremental-development

### ISSUE THREAD

**Issue by KLisabeth** [HackYourFutureBelgium/class-8#82]
### Prep Work
 

- [x] git & github for poets - watch through 1.4
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
- [x] Familiarize yourself with GitKraken
- [x] Study this example project( built-with-branches )
- [x] Understand how to use Atomic Commits
- [x] User Stories ( What Agile is & Progressive work slices)
- [x] Relative vs. Absolute Paths
- [x] How the Internet Works in 5 Minutes
- [x] How do Web Browsers Work?
- [x] Code Review
- [x] Lesson Plan ( slideshow )

### Project

- [x] 1. Start an empty repository called acme-web-design (Named exactly this!)
- [x] 2. Create an issue for this week's project in your class repo
- [x] 3. Move it to the "In Progres" column of this module's project board.
- [x] 4. Open the Responsive Layout tutorial video.
- [x] 5. Begin coding!

### acme-web-design

- [repository](https://github.com/KLisabeth/acme-web-design)
- [live demo](https://KLisabeth.github.io/acme-web-design)
- [x]  [created homepage with 6 commits](https://github.com/KLisabeth/acme-web-design/pull/1)
- [x]  [ created second page with 4 commits ](https://github.com/KLisabeth/acme-web-design/pull/2) 
- [x]  [ created service page with 5 commits ](https://github.com/KLisabeth/acme-web-design/pull/3)
- [x]  [ added images](https://github.com/KLisabeth/acme-web-design/pull/5) was my mistake to add it first *
- [x]  [ added css stylesheet with 2 commits ](https://github.com/KLisabeth/acme-web-design/pull/4)
### Exercises:

- [x] FreeCodeCamp: [ Life public portfolio with complete 22 challenges. ](https://www.freecodecamp.org/fcca71dbe28-96dc-452d-a5c6-2606e10c87c5)
- [x] HTML-CSS-Practice-Problems:Level 1 [repo](https://github.com/KLisabeth/HTML-CSS-Practice-Problems), [live]()
- [x] css-exercises: exercise-1 [repo](https://github.com/KLisabeth/css-exercises/blob/master/exercise-1), [live](https://klisabeth.github.io/css-exercises/exercise-1/)
- [x] css-exercises: exercise-2 [repo](https://github.com/KLisabeth/css-exercises/tree/master/exercise-2), [live](https://klisabeth.github.io/css-exercises/exercise-2/)

![Screenshot 2020-01-14 at 18 18 06](https://user-images.githubusercontent.com/58074853/72366395-7c19a200-36fa-11ea-9d6e-0acdd4286a88.png)
   
* Screenshot from [Learn Git Branching](https://learngitbranching.js.org) 

![Screenshot 2020-01-14 at 18 28 06](https://user-images.githubusercontent.com/58074853/72367123-f26ad400-36fb-11ea-828a-2cfa0c3ea8b0.png)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by idogrusoz** [comment]
https://klisabeth.github.io/acme-web-design/services.html on 'get a quote' section input fields don't stretch properly.

**Comment by KLisabeth** [comment]
Hopefuly it's fixed , and now will stretch properly ;)

**Comment by idogrusoz** [comment]
Well done. Good work with nice branching. Your issue page is detailed too. 
You may consider writing more informative  read me files.

Keep being motivated. You are doing very good.
