### ISSUE TITLE
ayseakyol: Week 1, Incremental Development

### ISSUE THREAD

**Issue by ayseakyol** [HackYourFutureBelgium/class-8#84]
### Prep Work

- [x]  git & github for poets - watch through 1.4
 - [x] LearnGitBranching & video tutorial - complete the first set of exercises
![](https://raw.githubusercontent.com/ayseakyol/ayseakyol.github.io/master/screenshot/gitbranching.png)
- [x] Familiarize yourself with GitKraken
    Study this example project
- [x] Understand how to use Atomic Commits
- [x] Agile Development by Cartoon
- [x] Splitting User Stories
- [x] The "what" not the "how"
relative vs. absolute paths
- [x] How the Internet Works in 5 Minutes
- [x] How do Web Browsers Work?
- [x] Code Review

### Name of Project:
__Acme-Web-Design__

- [repository](https://github.com/ayseakyol/acme-web-design)
- [live demo](https://ayseakyol.github.io/acme-web-design/)
- [x]  [step 1-starting](https://github.com/ayseakyol/acme-web-design/pull/1/files)
- [x]  [step 2-Header-Footer](https://github.com/ayseakyol/acme-web-design/pull/2/files)
- [x]  [step 3-Main-Area](https://github.com/ayseakyol/acme-web-design/pull/3/files)
- [x]  [step 4-About-Page](https://github.com/ayseakyol/acme-web-design/pull/4/files)
- [x]  [step 5-Services-Page](https://github.com/ayseakyol/acme-web-design/pull/5/files)
- [x]  [step 6-Get-a-Quote-Form](https://github.com/ayseakyol/acme-web-design/pull/6/files)
- [x]  [step 7-Responsive-Layout](https://github.com/ayseakyol/acme-web-design/pull/7/files)

### Exercises:

- [x]  Applied Accessibility: [repo](https://www.freecodecamp.org/ayseakyol)
![](https://raw.githubusercontent.com/ayseakyol/ayseakyol.github.io/master/screenshot/accessability.png)
- [x] HTML-CSS-Practice-Problems: [repo](https://github.com/ayseakyol/HTML-CSS-Practice-Problems/tree/master/level-1), [live](https://ayseakyol.github.io/HTML-CSS-Practice-Problems/level-1/index.html)
- [x] css-exercises:
- [x] exercise-1:[repo](https://github.com/ayseakyol/css-exercises/tree/master/exercise-1), [live](https://ayseakyol.github.io/css-exercises/exercise-1/)
- [x] exercise-2: [repo](https://github.com/ayseakyol/css-exercises/tree/master/exercise-2), [live](https://ayseakyol.github.io/css-exercises/exercise-2/)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by idogrusoz** [comment]
Very good work.  I liked the branching and naming.
- Be more careful about indentation in your code(especially HTML files) and empty lines(especially CSS)
Keep up the good work and keep being motivated.
