### ISSUE TITLE
Mesut: Week 1, Question 2

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#92]
Why There is nothing when you merged a branch to master and then did new update and and push it again (without launching a new branch)?

**Comment by colevandersWands** [comment]
did you commit after your new change?

**Comment by MesutBE** [comment]
Yes I think, I am making it from GitKraken. I am making Push click. Then it says Pushed Successfully. And then nothing happens.

**Comment by MesutBE** [comment]
![Screenshot from 2020-01-16 10-16-52](https://user-images.githubusercontent.com/59531743/72510465-c8bfc300-3849-11ea-8ec9-6b8d7f23deff.png)
Before screenshot, I made an push with branch "AboutHTML-3" then merged it with master. And then I changed a line and staged changes and push it again. 

This is successfully pushed message. But there is no Pull Request in my repo.

**Comment by MesutBE** [comment]
![Screenshot from 2020-01-16 10-37-15](https://user-images.githubusercontent.com/59531743/72512334-2f45e080-384c-11ea-86bc-3017af90e5ad.png)

Now I create a new branch name "fixing" the commit window appeared.

**Comment by feridunAKYOL** [comment]
Not here..
After push can you send a screenshot of your repo

**Comment by MesutBE** [comment]
![Screenshot from 2020-01-16 10-44-59](https://user-images.githubusercontent.com/59531743/72513349-43d6a880-384d-11ea-8180-21a22ef8dbf8.png)

**Comment by MesutBE** [comment]
![Screenshot from 2020-01-16 10-57-55](https://user-images.githubusercontent.com/59531743/72514627-17239080-384f-11ea-916e-2265400c502f.png)

Now it is here. Because I create a fixing branch.

**Comment by Rashaali84** [comment]
**the normal logical sequance of creating a branch and pushing your new work is as follows :** 
1- you create a branch ( use git kraken or use git branch [branch-name] command in git bash terminal ), and then you make sure that your on this branch .. using ... git checkout [branch-name]  
2- now you are sure that you are NOT on master branch ... and you are sure that you are on the newly created branch let's say its name is BugFix* <----- it should look like that with a star on the top
3- do the updates on code that you want
4- now it is time to stage your changes ..so stage changes 
5- then commit your changes and don't forget to write a message for that commit 
6- now it is time to push your work to the remote repo ... (sometimes you will be asked to make a pull request before pushing your new updates )

that is it ! .. these are the logical steps of the whole process ...I hope it is clear ?

**Comment by MesutBE** [comment]
![Screenshot from 2020-01-16 16-03-52](https://user-images.githubusercontent.com/59531743/72536031-d1c88880-3879-11ea-912a-b57a5aa4e21c.png)

I find something with this problem. You can see New Pull Request window, I think I forget something in the proccess.

I see your steps, but in the terminal commands, I don't understand all the procedures clearly.
I know it will solve my problem on the computer but not in my head :)

**Comment by MesutBE** [comment]
It solved on the class, thank you all.
