### ISSUE TITLE
Rasha Ali: Week 2 , Incremental-Development

### ISSUE THREAD

**Issue by Rashaali84** [HackYourFutureBelgium/class-8#95]
### Prep Work

- [x] Inspecting the DOM 
    - [x]    “Inspecting the DOM with your browser’s Developer Tools”
    - [x]    Practice through https://janke-learning.org/dom-tutor/
- [x] HTML & CSS
    - [x]     [What is Responsive Design?](https://www.youtube.com/watch?v=5KGah8bW8GE)
- [x] [Code Review](https://study.hackyourfuture.be/programming/code-review)
- [x] Git, GitHub & GitKraken

### This week's project is to study the **app-theme** tutorial from Traversy Media.

- [x] [live demo](https://rashaali84.github.io/app-theme/)
- [x] [README.md](https://github.com/Rashaali84/app-theme/blob/master/README.md )
- [x]  [repository](https://github.com/Rashaali84/app-theme)
- [x] [development-strategy.md](https://github.com/Rashaali84/app-theme/blob/master/development-strategy.md)

### Branches:
- [x]  [branch 1 -  add-meta-header-footer](https://github.com/Rashaali84/app-theme/tree/add-meta-header-footer)
- [x]  [branch 2 - create-basic-folders-pages ](https://github.com/Rashaali84/app-theme/tree/create-basic-folders-pages)
- [x]  [branch 3 - add-middlesections-indexpage](https://github.com/Rashaali84/app-theme/tree/add-middlesections-indexpage)
- [x]  [branch 4 - update-stylefile-forindexpage ](https://github.com/Rashaali84/app-theme/tree/update-stylefile-forindexpage)
- [x]  [branch 5 - update-about-htmlpage ](https://github.com/Rashaali84/app-theme/tree/update-about-htmlpage)
- [x]  [branch 6 - update-services-htmlpage](https://github.com/Rashaali84/app-theme/tree/update-services-htmlpage)
- [x]  [branch 7 - update-contact-htmlpage](https://github.com/Rashaali84/app-theme/tree/update-contact-htmlpage)
- [x]  [branch 8 - update-style-linkedpages](https://github.com/Rashaali84/app-theme/tree/update-style-linkedpages)
- [x]  [branch 9 - add-style-mediaqueries](https://github.com/Rashaali84/app-theme/tree/add-style-mediaqueries)

### Exercises:

- [x] [Complete all 4 of FreeCodeCamp's Responsive Web Design Principles  challenges.](https://www.freecodecamp.org/fcc88db250e-a8f1-4485-b2c3-564b72e8bf80) .
- [x] Complete HTML-CSS-Practice-Problems : the exercises in ./level-2 
     - [x]  [repo](https://github.com/Rashaali84/HTML-CSS-Practice-Problems/tree/master/level-2)
     - [x]   [live](https://rashaali84.github.io/HTML-CSS-Practice-Problems/level-2/)
- [x] Complete css-exercises: exercise-3 
     - [x] [repo](https://github.com/Rashaali84/css-exercises/tree/master/exercise-3)
     - [x]   [live](https://rashaali84.github.io/css-exercises/exercise-3/)
- [x] Complete css-exercises: exercise-4 
     - [x]  [repo](https://github.com/Rashaali84/css-exercises/tree/master/exercise-4)
     - [x]   [live](https://rashaali84.github.io/css-exercises/exercise-4/)
- [x] Complete css-exercises: exercise-5 
     - [x]  [repo](https://github.com/Rashaali84/css-exercises/tree/master/exercise-5)
     - [x]   [live](https://rashaali84.github.io/css-exercises/exercise-5/)

**Comment by idogrusoz** [comment]
Very well done.  Amazing detailed work.
