### ISSUE TITLE
KLisabeth: Week 2, incremental development

### ISSUE THREAD

**Issue by KLisabeth** [HackYourFutureBelgium/class-8#96]
### Prep Work
- [x] [Read through this site](https://hackyourfuture.be/inspecting-the-dom/)
- [x] Practice studying some HTML/CSS 
- [x] What is Responsive Design?
- [x] Git & github for poets
- [x] LearnGitBranching  
- [x] Familiarize yourself with GitKraken
- [x] Study [this](https://github.com/hackyourfuturebelgium/built-with-branches) example project
- [x] Understand how to use Atomic Commits
 
### Project

- [x] Create README describing your project in detail
- [x] One well-named branch per user story. 
- [x] Create file `development-strategy.md` & explain how you broke the project into user stories.
- [x] Start an empty repository called app-theme (Named exactly this!)
- [x] Create an issue for this week's project [just like this](https://github.com/HackYourFutureBelgium/homework-submission#homework-issues)
- [x] Move it to the "In Progres" column of this module's project board.
- [x] Open the [Responsive Template](https://www.youtube.com/watch?v=qlA7dputiNc) tutorial.
- [x] Begin studying!

### app-theme
- [x] [repo](https://github.com/KLisabeth/app-theme)
- [x] [life demo](https://klisabeth.github.io/app-theme/)
- [x] [create project plan](https://github.com/KLisabeth/app-theme/pull/1)
- [x] [created `home-page`](https://github.com/KLisabeth/app-theme/pull/2)
- [x] [create `about-page`](https://github.com/KLisabeth/app-theme/pull/3)
- [x] [create `services-page`](https://github.com/KLisabeth/app-theme/pull/4)
- [x] [create `contact-page`](https://github.com/KLisabeth/app-theme/pull/5) 
- [x] [create `final-touches`](https://github.com/KLisabeth/app-theme/pull/6) 
- [x] made some fixing [here](https://github.com/KLisabeth/app-theme/pull/7) [and here](https://github.com/KLisabeth/app-theme/pull/8)

### Exercises
- [x] Complete all 4 of FreeCodeCamp's [Responsive Web Design Principles challenges.](https://www.freecodecamp.org/fcca71dbe28-96dc-452d-a5c6-2606e10c87c5 )
- [ ] Fork and Clone HTML-CSS-Practice-Problems `./level-2`
- [ ] Complete `exercise-3`, `exercise-4` and `exercise-5`

![Screenshot 2020-01-14 at 18 18 06](https://user-images.githubusercontent.com/58074853/72980015-eeb10e80-3dd9-11ea-9c0f-c13a3cdfff25.png)

**Comment by otagi** [comment]
Very good user stories! 👏 

The code indentation could be be improved here and there, but overall it's well structured and organised.

One branch per user story, that's perfect. Be sure to always create a new branch from `master`, not from another feature branch (unless there is a good reason to do so, of course).
