### ISSUE TITLE
AyseAkyol:Week 2, Incremental Development

### ISSUE THREAD

**Issue by ayseakyol** [HackYourFutureBelgium/class-8#97]
#### Inspecting the DOM
- [x]  Read through this site
- [x]  And practice studying some HTML/CSS here
#### HTML & CSS
- [x] What is Responsive Design?

### Name of Project: app-theme

- [repository](https://github.com/ayseakyol/app-theme)
- [live demo](https://ayseakyol.github.io/app-theme/)
- [x]  [html-content](https://github.com/ayseakyol/app-theme/pull/1/files)
- [x]  [header-showcase](https://github.com/ayseakyol/app-theme/pull/2/files)
- [x]  [features-info](https://github.com/ayseakyol/app-theme/pull/3/files)
- [x]  [company-footer](https://github.com/ayseakyol/app-theme/pull/4/files)
- [x]  [about-page](https://github.com/ayseakyol/app-theme/pull/5/files)
- [x]  [services-page](https://github.com/ayseakyol/app-theme/pull/6/files)
- [x]  [contact-page](https://github.com/ayseakyol/app-theme/pull/7/files)

### Exercises:

- [x] **Responsive Web Design Principles** 
![](https://raw.githubusercontent.com/ayseakyol/ayseakyol.github.io/master/screenshot/responsiveness.png)
- [x] **HTML-CSS-Practice-Problems** : [repo](https://github.com/ayseakyol/HTML-CSS-Practice-Problems/pull/6/files), [live](https://ayseakyol.github.io/HTML-CSS-Practice-Problems/level-2/)
- [x] **css-exercises**:
  - [x] exercise-3: [repo](https://github.com/ayseakyol/css-exercises/pull/2/files), [live](https://ayseakyol.github.io/css-exercises/exercise-3/)
  - [ ] exercise-4
  - [ ] exercise-5

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by idogrusoz** [comment]
- Good and clean code.
- Good branching.

- The development strategy is missing. 
- Repository README can be more detailed. 9Don't hesitate to check the work of other students.0

**Comment by ayseakyol** [comment]
Thank you for your checking.
I changed my README and development strategy part and I put my card again
revision board.
Beste regards

**Comment by idogrusoz** [comment]
Very good work
