### ISSUE TITLE
 OmerSnck: Week 2 , Incremental-Development

### ISSUE THREAD

**Issue by OmerSnck** [HackYourFutureBelgium/class-8#98]
#### Inspecting the DOM
- [x]  Read through this site
- [x]  Practice studying some HTML/CSS 
- [x] What is Responsive Design?

###  Project:
- [x] [README.md]
- [x]  [Branch Per User Story]
- [x] [Development-strategy.md ] 
- [x] [live demo](https://omersnck.github.io/app-theme/)

### Exercises of Week 2::
- [x] [Complete all 4 of FreeCodeCamp'sResponsive Web Design Principles challenges.](https://www.freecodecamp.org/omersnck)
- [x] HTML-CSS-Practice-Problems `./level-2`: [repo](https://github.com/OmerSnck/HTML-CSS-Practice-Problems/tree/master/level-2), [live (if there is)]()
- [ ] CSS Exercises Complete `exercise-3`, `exercise-4` and  `exercise-5` : [repo](https://github.com/user-name/repo-name), [live (if there is)]()

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by idogrusoz** [comment]
- No live demo
- No development strategy.
- Branch names should be in kebab-case.
- You have unmerged branches.
- Improve the README of your repository

**Comment by idogrusoz** [comment]
- Live demo is accessible through repository but you should provide a link here in the issue too.
- Your main page has no background image.

**Comment by idogrusoz** [comment]
I believe that you can do much more better than this!

**Comment by OmerSnck** [comment]
![Screenshot 2020-01-23 at 23 03 59](https://user-images.githubusercontent.com/59530933/73028648-41b8af00-3e36-11ea-9409-f0f8019a95bd.png)

**Comment by idogrusoz** [comment]
Now see it. Maybe it was something with my browser. Sorry for that

**Comment by OmerSnck** [comment]
i have noticed what my false about background page is. i named different name for images as "img" and i changed and it works now on visual studio but not on my live demo. it is still as previous

**Comment by idogrusoz** [comment]
Strange enough that now I see it.

**Comment by OmerSnck** [comment]
> Now see it. Maybe it was something with my browser. Sorry for that

estagfurullah this is my fault sorry i dont know what this word in english is:)

**Comment by idogrusoz** [comment]
There are no such nice words in English ;)

**Comment by OmerSnck** [comment]
You have unmerged branches
Actually i was afraid of making mistake and damage my assignment when i am thinking merge. Especially towards the final steps

**Comment by OmerSnck** [comment]
but i will try right now without fear

**Comment by idogrusoz** [comment]
No worries. This is what is about git. You can go back to any previous commit if you want.

**Comment by idogrusoz** [comment]
You should learn how to create a pull request and compare before a merge

**Comment by OmerSnck** [comment]
Branch names should be in kebab-case.
i will rename them

**Comment by OmerSnck** [comment]
Improve the README of your repository.
Thank you very much for your feedback

**Comment by idogrusoz** [comment]
You are welcome. I hope that I am being helpful
